# Generated by Django 4.0.3 on 2022-03-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_alter_slider_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='photo',
            new_name='photo_link',
        ),
    ]
