# Generated by Django 4.0.3 on 2022-03-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_rename_photo_slider_photo_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('CEO', 'CEO'), ('FRONTEND', 'frontend'), ('BACKEND', 'backend')], max_length=200)),
                ('linkedin_link', models.CharField(blank=True, max_length=200, null=True)),
                ('fb_link', models.CharField(blank=True, max_length=200, null=True)),
                ('photo_link', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
