# Generated by Django 4.0.3 on 2022-03-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtuber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveSmallIntegerField()),
                ('city', models.CharField(max_length=200)),
                ('height', models.FloatField()),
                ('subs_count', models.PositiveBigIntegerField()),
                ('price', models.PositiveBigIntegerField()),
                ('photo_link', models.CharField(max_length=200)),
                ('video_link', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('crew', models.CharField(choices=[('small', 'SMALL'), ('solo', 'SOLO'), ('large', 'LARGE')], max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50)),
                ('camera_type', models.CharField(choices=[('panasonic', 'PANASONIC'), ('cannon', 'CANNON'), ('hasselblad', 'HASSELBLAD'), ('red', 'RED'), ('nikon', 'NIKON')], max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
