# Generated by Django 4.0.3 on 2022-03-04 15:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('panasonic', 'PANASONIC'), ('cannon', 'CANNON'), ('hasselblad', 'HASSELBLAD'), ('red', 'RED'), ('nikon', 'NIKON'), ('other', 'OTHER')], max_length=50),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('cooking', 'COOKING'), ('gaming', 'GAMING'), ('film making', 'VLOGGING'), ('film making', 'FILM MAKING'), ('other', 'OTHER')], max_length=50),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
